### ISSUE TITLE
Resolve peer dependency issue between react-router & history

### ISSUE THREAD

**Issue by topheman** [topheman/react-es6-redux#11]
This is on the branch https://github.com/topheman/react-es6-redux/tree/feature/record-http-fixtures

See https://travis-ci.org/topheman/react-es6-redux#L141

```
npm ERR! peerinvalid The package history@1.15.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.2 wants history@1.13.x
```

**Comment by topheman** [comment]
Fixed in https://github.com/topheman/react-es6-redux/commit/814797c3274482f3a4ba4a6d037b872a057d0020 - see build report : https://travis-ci.org/topheman/react-es6-redux/builds/95864580

**Comment by justjacksonn** [comment]
So is the fix for this right now to clone the repo build it etc? Or is there a solution via npm install that we can use? Sorry.. not a pro with all this building or github projects locally and replacing what npm install installs.

**Comment by topheman** [comment]
It's fixed right now, in master, you can clone and npm install (the unit tests passed on the fix I submited less than 20hours ago)

**Comment by justjacksonn** [comment]
Ok.. so oddly enough.. I updated node to 5.2 and npm to 3.5 and did a fresh install of my project and strangely it works?? Last time I updated to node 5/npm 3 there were a bunch of issues. Anyway, I am still seeing that issue but my code actually starts now. Sometimes this node/npm/etc stuff baffles me.

**Comment by topheman** [comment]
I haven't tested on node 5 / npm 3 yet.

On npm 3, this is normal if you have a warning about peerDependencies (since they are not allowed any more), but this should work anyway (since I include the packages with the right version anyway)

If it didn't work last time, the reason is react-router changed the version of `history` in its peerDependencies but history was already 2 minor versions ahead, so, I assume some people may have had the same kind of bug for a few days (I discovered it via my CI which broke last night, so I fixed the bug).

**Comment by justjacksonn** [comment]
Right.. I assume react-router needs to fix/update on their side.

**Comment by topheman** [comment]
As always, the answer is in the doc : https://github.com/rackt/react-router#installation

```
$ npm install history@1.13.1 react-router@latest
```

For the moment, the v1.0.2 needs `history@1.13.1` https://github.com/rackt/react-router/blob/v1.0.2/package.json#L44 but in near futur (days, for the v1.1.x of react router, they will rely on `history@1.15.x` https://github.com/rackt/react-router/commit/e24c382cbcafbbafeb27b78db804b4d14dc8a21f )

We have the explanation ... 😉

Tophe
